config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'log-in',
               sign_out: 'log-out'
             }

  namespace :admin do
    get '/', to: 'home#index'

    resources :albums
    resources :categories
    resources :tags
    resources :redirects

    resources :contributor_profiles, path: 'contributor-profiles'
    resources :users

    resources :news_entries, path: 'news-entries'
    resources :pages
    resources :pictures
    resources :music_tracks, path: 'music-tracks'
    resources :videos
    resources :downloads
  end

  namespace :api do
    namespace :v1 do
      get '/home', to: 'home#show'
      resources :categories, only: :show
      resources :contributions, only: :index
      resources :contributor_profiles, only: :show, path: 'contributors'
      resources :downloads, only: %i[index show]
      resources :literature, only: %i[index show] do
        resources :chapters, only: :show
      end
      resources :music_tracks, only: %i[index show], path: 'music'
      resources :news_entries, only: %i[index show], path: 'news'
      resources :pictures, only: %i[index show]
      resources :tags, only: :show
      resources :top_level_pages, only: :show, path: 'top-level-pages'
      resources :videos, only: %i[index show]
    end
  end

  get '/', to: 'home#show'
  resources :search, only: :index
  resources :categories, only: :show
  resources :contributions, only: :index
  resources :news_entries, only: %i[index show], path: 'news'
  resources :pictures, only: :show
  resources :literature, only: :show do
    resources :chapters, only: :show
  end
  resources :music_tracks, path: 'music', only: :show
  resources :videos, only: :show
  resources :downloads, only: :show

  resources :contributor_profiles, only: :show, path: 'contributors' do
    resources :news_entries, only: :index, path: 'news-entries'
    resources :pictures, only: :index
    resources :literature, only: :index
    resources :music_tracks, path: 'music-tracks', only: :index
    resources :videos, only: :index
    resources :downloads, only: :index
  end

  resources :tags, only: :show do
    resources :news_entries, only: :index, path: 'news-entries'
    resources :pictures, only: :index
    resources :literature, only: :index
    resources :music_tracks, path: 'music-tracks', only: :index
    resources :videos, only: :index
    resources :downloads, only: :index
  end

  get ':id', to: 'top_level_pages#show', as: 'top_level_page'
  root to: 'home#show'
end

app/models/video.rb
class Video < ApplicationRecord
  include Categorisable
  include Contributable
  include Publishable
  include Taggable
  include SluggableWithId
  include Syncable

  has_paper_trail

  belongs_to :album, optional: true

  validates :name, presence: true, length: { in: 2..100 }
  validates :description, presence: true, length: { in: 2..250 }
  validates(
    :sequence_number,
    presence: true,
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 999
    }
  )

  has_attached_file(
    :mp4_video,
    path: ':rails_root/public/system/:attachment/:id/:style/:filename',
    url: '/system/:attachment/:id/:style/:filename'
  )
  has_attached_file(
    :video_picture,
    styles: {
      mini_thumbnail: '25x25#',
      thumbnail: '150x150',
      embedded: '280x280>'
    },
    path: ':rails_root/public/system/:attachment/:id/:style/:filename',
    url: '/system/:attachment/:id/:style/:filename'
  )

  validates_attachment(
    :mp4_video,
    presence: true,
    size: {
      in: 0..500.megabytes
    }
  )
  validates_attachment(
    :video_picture,
    content_type: {
      content_type: 'image/jpeg'
    },
    size: {
      in: 0..5.megabytes
    }
  )

  # There were issues specifying content types.
  do_not_validate_attachment_file_type :mp4_video

  before_save :set_published_at
  before_save :set_slug
  before_save :sync_file_names
  before_save :strip_youtube_url_to_just_id

  def sync_file_names
    sync_file_name_of :mp4_video, file_name: "#{slug_from_name}.mp4"
    sync_file_name_of :video_picture, file_name: "#{slug_from_name}.jpg"
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name publish created_at updated_at published_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[category]
  end

  private

  def strip_youtube_url_to_just_id
    if self.youtube_video_id
      self.youtube_video_id =
        self.youtube_video_id.sub('https://www.youtube.com/watch?v=', '')
    end
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  include FindBySlugConcerns
  include LoadableForAlbumable
  include LoadableForVideo
  include PreviewSlugConcerns
  layout 'admin'
  before_action :load_albums, except: %i[index destroy]
  before_action :load_categories, except: %i[show destroy]
  before_action :load_video, except: %i[index new create]
  helper_method :custom_video_path

  def index
    clean_publish_false_param
    @q = Video.order(:name).ransack(params[:q])
    @videos = policy_scope(@q.result.includes(:category).page(params[:page]))
  end

  def new
    if params[:category]
      category = find_category_by_slug params[:category]
      @video = Video.new category: category
    else
      @video = Video.new
    end
    authorize @video
  end

  def create
    make_current_user_a_contributor unless current_user.administrator?
    @video = Video.new video_params
    authorize @video
    if @video.save
      flash[:notice] = 'Successfully created video.'
      redirect_to_video
    else
      render :new
    end
  end

  def update
    params[:video][:contributor_profile_ids] ||= []
    make_current_user_a_contributor unless current_user.administrator?
    if @video.update video_params
      flash[:notice] = 'Successfully updated video.'
      redirect_to_video
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to(admin_videos_path, notice: 'Successfully destroyed video.')
  end

  private

  def video_params
    params.require(:video).permit(policy(@video || :video).permitted_attributes)
  end

  def redirect_to_video
    if params[:continue_editing]
      redirect_to edit_admin_video_path(@video)
    else
      redirect_to custom_video_path(@video)
    end
  end

  def custom_video_path(video)
    custom_path(video, video_path(video))
  end

  def make_current_user_a_contributor
    unless current_user.contributor_profile_id.to_s.in?(
             params[:video][:contributor_profile_ids]
           )
      params[:video][:contributor_profile_ids] <<
        current_user.contributor_profile_id
    end
  end

  def sort_column
    Video.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end
end

app/controllers/api/v1/videos_controller.rb
class Api::V1::VideosController < ApplicationController
  include LoadableForVideo

  def index
    if params[:contributor_profile_id]
      load_contributors_videos
    elsif params[:tag_id]
      load_tagged_videos
    else
      @videos = policy_scope(Video.order(:name).page(params[:page]))
    end
    render template: 'api/v1/videos/index', formats: :json
  end

  def show
    load_video
    @tags =
      TagPolicy::Scope.new(
        current_user,
        Tag.where(name: @video.tags.map { |tag| tag.name }).order(:name)
      ).resolve
    render template: 'api/v1/videos/show', formats: :json
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include LoadableForVideo

  def index
    if params[:contributor_profile_id]
      load_contributors_videos
    elsif params[:tag_id]
      load_tagged_videos
    else
      @videos = policy_scope(Video.order(:name).page(params[:page]))
    end
  end

  def show
    load_video
    @tags =
      TagPolicy::Scope.new(
        current_user,
        Tag.where(name: @video.tags.map { |tag| tag.name }).order(:name)
      ).resolve
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def video_source_link_text(source_url)
    if source_url.include?('twitter.com') || source_url.include?('x.com')
      return 'X (Twitter)'
    end
    return 'YouTube' if source_url.include? 'youtube.com'
    'External Webpage'
  end
end

app/views/videos/_details.html.erb
<ul class="video__details">
  <% if @video.published_at %>
    <li>Published <%= local_date @video.published_at %></li>
  <% end %>
  <% unless @video.source_url.blank? %>
    <li>
      <%=
        link_to(
          "Source Video: #{video_source_link_text(@video.source_url)}",
          @video.source_url
        )
      %>
    </li>
  <% end %>
  <% unless @video.youtube_video_id.blank? %>
    <li>
      <%=
        link_to(
          'YouTube (Our Channel)',
          "https://www.youtube.com/watch?v=#{@video.youtube_video_id}"
        )
      %>
    </li>
  <% end %>
  <li><%= link_to 'Download MP4', @video.mp4_video.url %></li>
</ul>

app/views/videos/index.html.erb
<% if @contributor_profile %>
  <% title "#{@contributor_profile.name}'s Videos" %>
<% elsif @tag %>
  <% title "Videos Tagged With #{@tag.name}" %>
<% else %>
  <% title 'Videos' %>
<% end %>

<% if @videos %>
  <%= render(
    partial: 'shared/videos',
    locals: { videos: @videos }
  ) %>
<% end %>

app/views/videos/show.html.erb
<% title @video.name %>
<% description @video.description %>
<% if @video.video_picture.present? %>
  <% open_graph_image(
    ENV['WEBSITE_URL'].chomp('/') + @video.video_picture.url(:original)
  ) %>
<% end %>

<% if policy(@video).edit? %>
  <p class="admin-section">
    <%= link_to 'Edit Video', edit_admin_video_path(@video) %>
    <% if @video.album && policy(@video.album).edit? %>
      | <%= link_to 'Edit Album', edit_admin_album_path(@video.album) %>
    <% end %>
  </p>
<% end %>

<% unless @video.publish && @video.category.publish %>
  <%= render partial: 'shared/draft' %>
  <p class="draft">
    Use this Markdown to embed the video in a news entry:
    <code>![](<%= @video.id %>-<%= @video.slug %>.mp4)</code>
  </p>
<% end %>

<article class="video">
  <header class="video__header">
    <% if @video.album && album_has_at_least_two_albumables(@video.album) %>
      <%= render(
        partial: 'shared/albums/navigation',
        locals: { albumable: @video }
      ) %>
    <% end %>
  </header>
  <div class="video__body">
    <div class="video__video">
      <video
        controls="true"
        autobuffer="true"
        poster="<%= @video.video_picture.url(:embedded) %>"
      >
        <source type="video/mp4" src="<%= @video.mp4_video.url %>" />
        Your browser does not support the <code>video</code> element.
      </video>
    </div>
    <%= render(
      partial: 'shared/contributed_by',
      locals: { contributor_profiles: @video.contributor_profiles }
    ) %>
    <%= render(
      partial: 'videos/details',
      locals: { video: @video }
    ) %>
    <p class="video__description">
      <%= @video.description %>
    </p>
    <% unless @video.information.blank? %>
      <div class="video__extra-information">
        <%= raw markdown_to_html @video.information %>
      </div>
    <% end %>
  </div>
  <footer class="video__footer">
    <% if @video.album && album_has_at_least_two_albumables(@video.album) %>
      <%= render(
        partial: 'shared/albums/album',
        locals: { album: @video.album, picture_id: nil, video_id: @video.id }
      ) %>
    <% end %>
    <%= render(
      partial: 'shared/related_tags',
      locals: { tags: @tags }
    ) %>
  </footer>
</article>